version: '3.8'

services:
  bot:
    build: .
    container_name: daily-budget-bot
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - GOOGLE_SHEETS_ID=${GOOGLE_SHEETS_ID}
      - GOOGLE_CREDENTIALS_PATH=/app/credentials/service-account-key.json
    volumes:
      - ./src/services/credentials:/app/credentials:ro
      - bot-data:/app/data
    networks:
      - bot-network

volumes:
  bot-data:

networks:
  bot-network:
    driver: bridge
